/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"
#include <stdio.h>
#include <stdlib.h>


void
calculadora_1(char *host)
{
	CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int *result;
	entrada param;
	int opcion;

	printf("Ingrese su primer número\n");
	scanf("%d",&(param.arg1));
	printf("Ingrese su segundo número\n");
	scanf("%d",&(param.arg2));
	printf("¿Qué es lo que desea hacer:\n");
	printf("\t1. Suma\n");
	printf("\t2. Resta\n");
	printf("\t3. Multiplicación\n");
	printf("\t4. Divisioón\n");
	scanf("%d",&opcion);
	switch (opcion) {
		case 1:
			result = sumar_1(&param, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Fallo en la llamada a sumar_1");
			}
			else{
				printf("El resultado es %d\n",*result);
			}
		break;
		case 2:
			result = restar_1(&param, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Fallo en la llamada a restar_1");
			}
			else{
				printf("El resultado es %d\n",*result);
			}
		break;
		case 3:
			result = multiplicar_1(&param, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Fallo en la llamada a multiplicar_1");
			}
			else{
				printf("El resultado es %d\n",*result);
			}
		break;
		case 4:
			result = dividir_1(&param, clnt);
			if (result == (int *) NULL) {
				clnt_perror (clnt, "Fallo en la llamada a dividir_1");
			}
			else{
				printf("El resultado es %d\n",*result);
			}
		break;
		default:
			printf("Error al seleccionar una opción\n");
		break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host);
exit (0);
}
